# Generated by Django 5.2.13 on 2026-04-14 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tests_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TestAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("attempt_number", models.PositiveIntegerField(default=1)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "auto_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "manual_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "total_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("is_overdue", models.BooleanField(default=False)),
                ("essay_review_pending", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="tests_app.test",
                    ),
                ),
            ],
            options={
                "unique_together": {("test", "student", "attempt_number")},
            },
        ),
        migrations.CreateModel(
            name="AttemptAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("answer_payload", models.JSONField(default=dict)),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                (
                    "auto_points",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "manual_points",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("teacher_comment", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "test_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempt_answers",
                        to="tests_app.testquestion",
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="attempts.testattempt",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
